apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: epicalendar

resources:
    - namespace.yaml
    - mongodb-pvc.yaml
    - mongodb-secret.yaml
    - app-secret.yaml
    - mongodb-configmap.yaml
    - mongodb-deployment.yaml
    - server-deployment.yaml
    - client-deployment.yaml
    - ingress.yaml
# Note: commonLabels/labels are removed because they modify immutable selector fields
# Labels are already defined in individual deployment manifests

