apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: epicalendar

resources:
  - namespace.yaml
  - mongodb-pvc.yaml
  - mongodb-secret.yaml
  - app-secret.yaml
  - mongodb-configmap.yaml
  - mongodb-deployment.yaml
  - server-deployment.yaml
  - client-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: epicalendar
  app.kubernetes.io/version: "1.0.0"
