apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: epicalendar
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongo
  MONGO_INITDB_ROOT_PASSWORD: mongo
  MONGO_INITDB_DATABASE: epicalendar_db
  MONGODB_URI: mongodb://mongo:mongo@mongodb-service:27017/epicalendar?authSource=admin
